/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author LionotRAZAFIMANDIMBY
 */
public class AjoutEmp extends javax.swing.JFrame {

    //code tana
    public static Connection connex = null;
    public static ResultSet resul = null;
    public static PreparedStatement prepare = null;
    //ending
    //code tana again
    public String civilite;

    static boolean instant;
    int xMouve;
    int yMouve;

    private PrincipalMenu principal;

    /**
     * Creates new form AjoutEmp
     */
    public AjoutEmp(PrincipalMenu principal) {
        initComponents();
        this.setLocationRelativeTo(null);
        connex = Connexion.DBConnexion.connex;
        this.principal = principal;
        instant = false;

        /////////// code transparent ///////////
        NumEmp.setOpaque(false);
        nomEmp.setOpaque(false);
        prenomEmp.setOpaque(false);
        posteEmp.setOpaque(false);
        lieuEmp.setOpaque(false);

    }

    private AjoutEmp() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        NumEmp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomEmp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prenomEmp = new javax.swing.JTextField();
        posteEmp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mrEmp = new javax.swing.JRadioButton();
        mlleEmp = new javax.swing.JRadioButton();
        mmeEmp = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        lieuEmp = new javax.swing.JTextField();
        jAddEmp = new javax.swing.JButton();
        jCancelEmp = new javax.swing.JButton();
        Closed = new javax.swing.JLabel();
        Mouve = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 83, 86));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 36));

        NumEmp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NumEmp.setForeground(new java.awt.Color(255, 255, 255));
        NumEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        NumEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(NumEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 260, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, 110, 40));

        nomEmp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomEmp.setForeground(new java.awt.Color(255, 255, 255));
        nomEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomEmp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(nomEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 260, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pronom:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 40));

        prenomEmp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prenomEmp.setForeground(new java.awt.Color(255, 255, 255));
        prenomEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prenomEmp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(prenomEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 260, 40));

        posteEmp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        posteEmp.setForeground(new java.awt.Color(255, 255, 255));
        posteEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posteEmp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        posteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posteEmpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(posteEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 260, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Poste:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Civilité:");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 100, 40));

        buttonGroup1.add(mrEmp);
        mrEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mrEmp.setForeground(new java.awt.Color(255, 255, 255));
        mrEmp.setText("Mr");
        mrEmp.setContentAreaFilled(false);
        mrEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrEmpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(mrEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 80, 25));

        buttonGroup1.add(mlleEmp);
        mlleEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mlleEmp.setForeground(new java.awt.Color(255, 255, 255));
        mlleEmp.setText("Mlle");
        mlleEmp.setContentAreaFilled(false);
        mlleEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlleEmpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(mlleEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 83, -1));

        buttonGroup1.add(mmeEmp);
        mmeEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mmeEmp.setForeground(new java.awt.Color(255, 255, 255));
        mmeEmp.setText("Mme");
        mmeEmp.setContentAreaFilled(false);
        mmeEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmeEmpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(mmeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 82, 31));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lieu:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 40));

        lieuEmp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lieuEmp.setForeground(new java.awt.Color(255, 255, 255));
        lieuEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lieuEmp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(lieuEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 260, 40));

        jAddEmp.setText("Ajouter");
        jAddEmp.setFocusPainted(false);
        jAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddEmpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 110, 41));

        jCancelEmp.setText("Annuler");
        jCancelEmp.setFocusPainted(false);
        jCancelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelEmpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jCancelEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, 100, 40));

        Closed.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Closed.setForeground(new java.awt.Color(248, 6, 6));
        Closed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Closed.setText("X");
        Closed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Closed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosedMouseClicked(evt);
            }
        });
        kGradientPanel1.add(Closed, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 30, 30));

        Mouve.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MouveMouseDragged(evt);
            }
        });
        Mouve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MouveMousePressed(evt);
            }
        });
        kGradientPanel1.add(Mouve, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isInstant() {
        return instant;
    }
    private void jCancelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelEmpActionPerformed
        instant = true;
        this.dispose();
    }//GEN-LAST:event_jCancelEmpActionPerformed

    private void posteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posteEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posteEmpActionPerformed

    private void mmeEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmeEmpActionPerformed
        civilite = "Mme";
        // TODO add your handling code here:
    }//GEN-LAST:event_mmeEmpActionPerformed

    private void jAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddEmpActionPerformed
        if (NumEmp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuiller remplir le champs numero");
        } else if (nomEmp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuiller remplir le champs nom");
        } else if (prenomEmp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuiller remplir le champs prenom");
        } else if (posteEmp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuiller remplir le champs poste");
        } else if (lieuEmp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuiller remplir le champs lieu");
        } else if (NumEmp.getText().startsWith(".") || NumEmp.getText().startsWith("+") || NumEmp.getText().startsWith("-") || NumEmp.getText().startsWith(",") || NumEmp.getText().startsWith("/") || NumEmp.getText().startsWith(";")) {
            JOptionPane.showMessageDialog(null, "Le numero du employes ne peut pas commencer par les symboles '+', '-', ou ','");
        } else if (nomEmp.getText().startsWith(".") || nomEmp.getText().startsWith("+") || nomEmp.getText().startsWith("-") || nomEmp.getText().startsWith(",")|| nomEmp.getText().startsWith("/") || nomEmp.getText().startsWith(";")) {
            JOptionPane.showMessageDialog(null, "Le nom du employes ne peut pas commencer par les symboles '+', '-', ou ','");
        } else if (posteEmp.getText().startsWith(".") || posteEmp.getText().startsWith("+") || posteEmp.getText().startsWith("-") || posteEmp.getText().startsWith(",")|| posteEmp.getText().startsWith("/") || posteEmp.getText().startsWith(";"))  {
            JOptionPane.showMessageDialog(null, "Le poste du employes ne peut pas commencer par les symboles '+', '-', ou ','");
        } else if (lieuEmp.getText().startsWith(".") || lieuEmp.getText().startsWith("+") || lieuEmp.getText().startsWith("-") || lieuEmp.getText().startsWith(",") || lieuEmp.getText().startsWith("/") || lieuEmp.getText().startsWith(";")) {
            JOptionPane.showMessageDialog(null, "Le lieu du employes ne peut pas commencer par les symboles '+', '-', ou ','");
        } else {
            try {

                String verify = "SELECT COUNT(*) FROM employes WHERE numEmp = ?";
                prepare = connex.prepareStatement(verify);
                prepare.setString(1, NumEmp.getText());
                resul = prepare.executeQuery();
                int count = 0;
                if (resul.next()) {
                    count = resul.getInt(1);
                }
                resul.close();
                prepare.close();
                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Le numero Employes '" + NumEmp.getText() + "' est deja existe ");
                    return;
                } else {
                    String request = "INSERT INTO employes (numEmp,civilite,nomEmp,prenomEmp,post,lieu) VALUES (?,?,?,?,?,?)";

                    prepare = connex.prepareStatement(request/*,Statement.RETURN_GENERATED_KEYS*/);
                    prepare.setString(1, NumEmp.getText());
                    prepare.setString(3, nomEmp.getText());
                    prepare.setString(4, prenomEmp.getText());
                    prepare.setString(5, posteEmp.getText());
                    prepare.setString(6, lieuEmp.getText());
                    prepare.setString(2, civilite);

                    /* int idDepartement =  -1;
                
                if(prepare.executeUpdate()>0){
                    resul = prepare.getGeneratedKeys();
                    if(resul.next()){
                        idDepartement =  resul.getInt(1);
                        System.out.println("ID="+resul.getInt(1));
                    }
                }*/
                    prepare.execute();
                    JOptionPane.showMessageDialog(null, "Ajout avac succes !!");
                }

            } catch (Exception e) {
                System.out.println(" -->SQLException : " + e);
            } finally {
                try {
                    prepare.close();
                    resul.close();
                } catch (Exception e) {

                }
            }
            instant = true;
            this.dispose();
        }


    }//GEN-LAST:event_jAddEmpActionPerformed

    private void mrEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrEmpActionPerformed
        civilite = "Mr";
        // TODO add your handling code here:
    }//GEN-LAST:event_mrEmpActionPerformed

    private void mlleEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlleEmpActionPerformed
        civilite = "Mlle";
        // TODO add your handling code here:
    }//GEN-LAST:event_mlleEmpActionPerformed

    private void ClosedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosedMouseClicked
        instant = true;
        this.dispose();
    }//GEN-LAST:event_ClosedMouseClicked

    private void MouveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouve, y - yMouve);
    }//GEN-LAST:event_MouveMouseDragged

    private void MouveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveMousePressed
        xMouve = evt.getX();
        yMouve = evt.getY();
    }//GEN-LAST:event_MouveMousePressed

    private void NumEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    //<editor-fold defaultstate="collapsed" desc="comment">
    public static void main(String args[]) {
//</editor-fold>
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AjoutEmp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closed;
    private javax.swing.JLabel Mouve;
    private javax.swing.JTextField NumEmp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAddEmp;
    private javax.swing.JButton jCancelEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField lieuEmp;
    private javax.swing.JRadioButton mlleEmp;
    private javax.swing.JRadioButton mmeEmp;
    private javax.swing.JRadioButton mrEmp;
    private javax.swing.JTextField nomEmp;
    private javax.swing.JTextField posteEmp;
    private javax.swing.JTextField prenomEmp;
    // End of variables declaration//GEN-END:variables
}
