/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;

/**
 *
 * @author LionotRAZAFIMANDIMBY
 */
public class AjoutDepartement extends javax.swing.JFrame {

    //code tana
    public static Connection connex = null;
    public static ResultSet resul = null;
    public static PreparedStatement prepare = null;

    static boolean ajoutValid;

    int xMouve;
    int yMouve;

//    private PrincipalMenu fenetrePrincipal;
    //ending
    /**
     * Creates new form AjoutDepartement
     */
    public AjoutDepartement() {
        initComponents();
        this.setLocationRelativeTo(null);
        connex = Connexion.DBConnexion.connex;
        ajoutValid = false;

        /////////// code transparent ///////////
        jNomdepartement.setOpaque(false);
        jDecrip.setOpaque(false);
        jPosteDepart.setOpaque(false);
        jLieuDepart.setOpaque(false);

        jAjoutDepart.setOpaque(false);
        jAnnulerDepart.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jNomdepartement = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDecrip = new javax.swing.JTextField();
        jAjoutDepart = new javax.swing.JButton();
        jAnnulerDepart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPosteDepart = new javax.swing.JTextField();
        jLieuDepart = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Closed = new javax.swing.JLabel();
        Mouve = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 83, 86));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jNomdepartement.setBackground(new java.awt.Color(73, 93, 100));
        jNomdepartement.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNomdepartement.setForeground(new java.awt.Color(255, 255, 255));
        jNomdepartement.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNomdepartement.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jDecrip.setBackground(new java.awt.Color(73, 93, 100));
        jDecrip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jDecrip.setForeground(new java.awt.Color(255, 255, 255));
        jDecrip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDecrip.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jAjoutDepart.setText("Ajouter");
        jAjoutDepart.setFocusPainted(false);
        jAjoutDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjoutDepartActionPerformed(evt);
            }
        });

        jAnnulerDepart.setText("Annuler");
        jAnnulerDepart.setFocusPainted(false);
        jAnnulerDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnnulerDepartActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Poste:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPosteDepart.setBackground(new java.awt.Color(73, 93, 100));
        jPosteDepart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPosteDepart.setForeground(new java.awt.Color(255, 255, 255));
        jPosteDepart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPosteDepart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPosteDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPosteDepartActionPerformed(evt);
            }
        });

        jLieuDepart.setBackground(new java.awt.Color(73, 93, 100));
        jLieuDepart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLieuDepart.setForeground(new java.awt.Color(255, 255, 255));
        jLieuDepart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLieuDepart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lieu:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Closed.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Closed.setForeground(new java.awt.Color(253, 4, 4));
        Closed.setText("X");
        Closed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Closed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosedMouseClicked(evt);
            }
        });

        Mouve.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MouveMouseDragged(evt);
            }
        });
        Mouve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MouveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(Mouve, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Closed)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDecrip, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jNomdepartement))
                        .addGap(9, 9, 9))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPosteDepart)
                                .addGap(9, 9, 9))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLieuDepart, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jAjoutDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jAnnulerDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Closed, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(Mouve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNomdepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDecrip, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPosteDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLieuDepart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAjoutDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAnnulerDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPosteDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPosteDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPosteDepartActionPerformed

    private void jAnnulerDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnnulerDepartActionPerformed
        ajoutValid = true;
        this.dispose();
    }//GEN-LAST:event_jAnnulerDepartActionPerformed

    public boolean isAjoutValid() {
        return ajoutValid;
    }
    private void jAjoutDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAjoutDepartActionPerformed
        if (jNomdepartement.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuiller remplir le champs nom departement");
        } else if (jDecrip.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuiller remplir le champs description de la departement");
        } else if (jPosteDepart.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuiller remplir le champs le poste existe dans le departement");
        } else if (jLieuDepart.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuiller remplir le champs Lieu ou on peut trouver le departement");
        } else if (jNomdepartement.getText().startsWith(".") || jNomdepartement.getText().startsWith("+") || jNomdepartement.getText().startsWith("-") || jNomdepartement.getText().startsWith(",") || jNomdepartement.getText().startsWith("/") || jNomdepartement.getText().startsWith(";")) {
            JOptionPane.showMessageDialog(null, "Le nom du département ne peut pas commencer par les symboles '+', '-', ou ','");
        } else if (jDecrip.getText().startsWith(".") || jDecrip.getText().startsWith("+") || jDecrip.getText().startsWith("-") || jDecrip.getText().startsWith(",") || jDecrip.getText().startsWith("/") || jDecrip.getText().startsWith(";")) {
            JOptionPane.showMessageDialog(null, "Le descripion du département ne peut pas commencer par les symboles '+', '-', ou ','");
        } else if (jPosteDepart.getText().startsWith(".") || jPosteDepart.getText().startsWith("+") || jPosteDepart.getText().startsWith("-") || jPosteDepart.getText().startsWith(",") || jPosteDepart.getText().startsWith("/") || jPosteDepart.getText().startsWith(";")) {
            JOptionPane.showMessageDialog(null, "Le poste du département ne peut pas commencer par les symboles '+', '-', ou ','");
        } else if (jLieuDepart.getText().startsWith(".") || jLieuDepart.getText().startsWith("+") || jLieuDepart.getText().startsWith("-") || jLieuDepart.getText().startsWith(",") || jLieuDepart.getText().startsWith("/") || jLieuDepart.getText().startsWith(";")) {
            JOptionPane.showMessageDialog(null, "Le lieu du département ne peut pas commencer par les symboles '+', '-', ou ','");
        } else {
            try {
                String request = "INSERT INTO departements (NomDepart,DescrDepart,LieuDepart,PosteExist) VALUES (?,?,?,?)";

                prepare = connex.prepareStatement(request, Statement.RETURN_GENERATED_KEYS);
                prepare.setString(1, jNomdepartement.getText());
                prepare.setString(2, jDecrip.getText());
                prepare.setString(3, jPosteDepart.getText());
                prepare.setString(4, jLieuDepart.getText());

                int idDepartement = -1;

                if (prepare.executeUpdate() > 0) {
                    resul = prepare.getGeneratedKeys();
                    if (resul.next()) {
                        idDepartement = resul.getInt(1);
                        System.out.println("ID=" + resul.getInt(1));
                        System.out.println("ID=" + idDepartement);
                    }
                }

                try {
                    String query = "INSERT INTO missions (idDepart_ref) VALUES ('" + idDepartement + "')";
                    prepare = connex.prepareStatement(query);
                    prepare.execute();
                    System.out.println("cle etranger est:" + query);
                } catch (Exception e) {
                    System.out.println(e);
                }

//                prepare.execute();
                JOptionPane.showMessageDialog(null, "Ajout avac succes !!");

            } catch (Exception e) {
                System.out.println(" -->SQLException : " + e);
            } finally {
                try {
                    prepare.close();
                    resul.close();
                } catch (Exception e) {

                }
            }
            ajoutValid = true;
            this.dispose();

        }

    }//GEN-LAST:event_jAjoutDepartActionPerformed

    private void ClosedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosedMouseClicked
        ajoutValid = true;
        this.dispose();
    }//GEN-LAST:event_ClosedMouseClicked

    private void MouveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouve, y - yMouve);
    }//GEN-LAST:event_MouveMouseDragged

    private void MouveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveMousePressed
        xMouve = evt.getX();
        yMouve = evt.getY();
    }//GEN-LAST:event_MouveMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutDepartement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutDepartement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutDepartement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutDepartement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutDepartement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closed;
    private javax.swing.JLabel Mouve;
    private javax.swing.JButton jAjoutDepart;
    private javax.swing.JButton jAnnulerDepart;
    private javax.swing.JTextField jDecrip;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jLieuDepart;
    private javax.swing.JTextField jNomdepartement;
    private javax.swing.JTextField jPosteDepart;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
