/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import static View.PrincipalMenu.connex;
import static View.PrincipalMenu.prepare;
import static View.PrincipalMenu.resul;
import java.awt.Dimension;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author LionotRAZAFIMANDIMBY
 */
public class ListeHisto extends javax.swing.JFrame {

    int xMouve;
    int yMouve;

    /**
     * Creates new form ListeHisto
     */
    public ListeHisto() {
        initComponents();
        this.setLocationRelativeTo(null);
        AffichageHisto();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jFermerHist = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHistorique = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Closed = new javax.swing.JLabel();
        Mouve = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 83, 86));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFermerHist.setText("Fermer");
        jFermerHist.setFocusPainted(false);
        jFermerHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFermerHistActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jFermerHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 150, 31));

        TableHistorique.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TableHistorique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Civilite", "AncienLieu", "NouveauLieu", "DateAfFectation", "DateService"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableHistorique.setRowHeight(40);
        jScrollPane1.setViewportView(TableHistorique);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 87, 700, 330));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Historique des affectations d’un employé");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 360, 31));

        Closed.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Closed.setForeground(new java.awt.Color(241, 9, 9));
        Closed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Closed.setText("X");
        Closed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Closed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosedMouseClicked(evt);
            }
        });
        kGradientPanel1.add(Closed, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 20, 40));

        Mouve.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MouveMouseDragged(evt);
            }
        });
        Mouve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MouveMousePressed(evt);
            }
        });
        kGradientPanel1.add(Mouve, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 690, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFermerHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFermerHistActionPerformed
        this.hide();
    }//GEN-LAST:event_jFermerHistActionPerformed

    private void ClosedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosedMouseClicked
        this.hide();
    }//GEN-LAST:event_ClosedMouseClicked

    private void MouveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouve, y - yMouve);
    }//GEN-LAST:event_MouveMouseDragged

    private void MouveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveMousePressed
        xMouve = evt.getX();
        yMouve = evt.getY();
    }//GEN-LAST:event_MouveMousePressed

    public void AffichageHisto() {
        try {
            String Query = "SELECT e.nomEmp AS \"NOM EMPLOYE\",e.prenomEmp AS \"PRENOM EMPLOYE\",e.civilite AS \"CIVILITE\",a.AncienLieu AS \"ANCIEN LIEU\",a.NouveauLieu  AS \"NOUVEAU LIEU\",a.dateAffect AS \"DATE AFFECTATION\",a.dateServices AS \"DATE SERVICE\" FROM employes e INNER JOIN affectations a ON e.lieu=a.AncienLieu ORDER BY a.dateAffect";
            prepare = connex.prepareStatement(Query);
            resul = prepare.executeQuery();
            TableHistorique.setModel(DbUtils.resultSetToTableModel(resul));

            // Créer un renvoie
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

        // Appliquer le renvoie à chaque colonne
            for (int i = 0; i < TableHistorique.getColumnCount(); i++) {
                TableHistorique.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
            
            JTableHeader header =TableHistorique.getTableHeader();
//            header.setForeground(Color.WHITE);
//            header.setBackground(Color.GRAY);

            Dimension dimension = header.getPreferredSize();
            dimension.height = 30;
            header.setPreferredSize(dimension);
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeHisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeHisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeHisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeHisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeHisto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closed;
    private javax.swing.JLabel Mouve;
    private javax.swing.JTable TableHistorique;
    private javax.swing.JButton jFermerHist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
