/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import static View.PrincipalMenu.connex;
import static View.PrincipalMenu.prepare;
import static View.PrincipalMenu.resul;
import java.awt.Dimension;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author LionotRAZAFIMANDIMBY
 */
public class ListeNonAffect extends javax.swing.JFrame {

    int xMouve;
    int yMouve;

    /**
     * Creates new form ListeNonAffect
     */
    public ListeNonAffect() {
        initComponents();
        this.setLocationRelativeTo(null);
        AffichageNonAffect();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListeEmployesNoAff = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jFermer = new javax.swing.JButton();
        Mouve = new javax.swing.JLabel();
        Closed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 83, 86));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableListeEmployesNoAff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableListeEmployesNoAff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Civilite", "Nom", "Prenom", "Poste", "Lieu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListeEmployesNoAff.setRowHeight(40);
        jScrollPane1.setViewportView(jTableListeEmployesNoAff);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 89, 700, 340));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Liste des personnes pas encore été affecté");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 370, 31));

        jFermer.setText("Fermer");
        jFermer.setFocusPainted(false);
        jFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFermerActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 116, 35));

        Mouve.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MouveMouseDragged(evt);
            }
        });
        Mouve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MouveMousePressed(evt);
            }
        });
        kGradientPanel1.add(Mouve, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 670, 30));

        Closed.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Closed.setForeground(new java.awt.Color(249, 16, 16));
        Closed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Closed.setText("X");
        Closed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Closed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosedMouseClicked(evt);
            }
        });
        kGradientPanel1.add(Closed, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFermerActionPerformed
        this.hide();
    }//GEN-LAST:event_jFermerActionPerformed

    private void ClosedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosedMouseClicked
        this.hide();
    }//GEN-LAST:event_ClosedMouseClicked

    private void MouveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouve, y - yMouve);
    }//GEN-LAST:event_MouveMouseDragged

    private void MouveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveMousePressed
        xMouve = evt.getX();
        yMouve = evt.getY();
    }//GEN-LAST:event_MouveMousePressed

    public void AffichageNonAffect() {
        try {
            String Query = "SELECT numEmp AS \" N EMPLOYES\",civilite AS \" CIVILITE\",nomEmp AS \"NOM EMPLOYES\",prenomEmp AS \" PRENOM EMPLOYES\",post AS \"POSTE\",lieu AS \"LIEU\" FROM employes WHERE lieu NOT IN(SELECT AncienLieu FROM affectations)";
            prepare = connex.prepareStatement(Query);
            resul = prepare.executeQuery();
            jTableListeEmployesNoAff.setModel(DbUtils.resultSetToTableModel(resul));

            // Créer un renvoie
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);


            for (int i = 0; i < jTableListeEmployesNoAff.getColumnCount(); i++) {
                jTableListeEmployesNoAff.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
            
            JTableHeader header = jTableListeEmployesNoAff.getTableHeader();
//            header.setForeground(Color.WHITE);
//            header.setBackground(Color.GRAY);

            Dimension dimension = header.getPreferredSize();
            dimension.height = 30;
            header.setPreferredSize(dimension);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeNonAffect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeNonAffect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeNonAffect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeNonAffect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeNonAffect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closed;
    private javax.swing.JLabel Mouve;
    private javax.swing.JButton jFermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListeEmployesNoAff;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
